/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Konsul extends javax.swing.JFrame {

    private int idUser; // ID User yang didapat saat login
    private String userName;
    private int selectedDoctorId; // Variabel untuk menyimpan ID dokter yang dipilih
    private int id_dokter;

    /**
     * Creates new form HomePage
     */
    public Konsul(int idUser, String userName) {
        initComponents();
        this.idUser = idUser; // Simpan ID User
        this.userName = userName; // Save user name
        loadPatientData();
        LoadNamaDokter();
        loadRiwayatKonsultasi(); // Load consultation history
        jIDUSER.setText(String.valueOf(idUser)); // Set ID in text field
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Riwayat = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        BAYAR = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        dr = new javax.swing.JComboBox<>();
        jIDUSER = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detaildokter = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        delete2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Pictures\\AAA\\Halo__1_-removebg-preview.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 70));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel3.setText("healthMate");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Pictures\\AAA\\data.png")); // NOI18N
        jLabel5.setText("Profil");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 120, 60));

        jLabel39.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel39.setText("Layanan Cepat dan Tepat");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Konsultasi Kesehatan terpercaya sejak 2005");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Pictures\\AAA\\1.jpg")); // NOI18N
        jLabel22.setText("jLabel21");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1390, -1));

        Riwayat.setBackground(new java.awt.Color(211, 233, 255));
        Riwayat.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Konsultasi"));

        jPanel6.setBackground(new java.awt.Color(211, 233, 255));
        jPanel6.setLayout(null);

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Pictures\\AAA\\a1.png")); // NOI18N
        jPanel6.add(jLabel31);
        jLabel31.setBounds(-10, 0, 70, 70);

        jLabel6.setText("Nama ");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(10, 90, 120, 16);

        jLabel8.setText("Dokter");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(10, 130, 120, 16);

        jLabel9.setText("Tempat Tanggal Lahir");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(10, 170, 120, 20);

        jLabel11.setText("Jenis Kelamin");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(10, 210, 160, 16);

        jLabel12.setText("Alamat");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 250, 120, 16);

        jLabel13.setText("Keluhan");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 330, 130, 16);

        jLabel14.setText("Alergi : ");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 430, 40, 16);

        jTextField1.setText(" ");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(jTextField1);
        jTextField1.setBounds(140, 90, 190, 22);

        jTextField3.setText(" ");
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3);
        jTextField3.setBounds(340, 170, 50, 22);

        jTextField4.setText(" ");
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(jTextField4);
        jTextField4.setBounds(140, 210, 190, 22);

        jTextField5.setText(" ");
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(jTextField5);
        jTextField5.setBounds(140, 250, 190, 22);

        jTextField8.setText(" ");
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(jTextField8);
        jTextField8.setBounds(140, 420, 200, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(140, 280, 350, 130);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\next.png")); // NOI18N
        jButton1.setText("Lanjutkan ke pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(490, 450, 210, 23);

        jInternalFrame1.setVisible(false);

        jLabel16.setText("Pilih Metode : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "BNI", "BRI", "DANA", "BCA" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        BAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAYARActionPerformed(evt);
            }
        });

        jButton2.setText("Konfirmasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jDesktopPane1);
        jDesktopPane1.setBounds(800, 20, 420, 360);

        dr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Dokter---" }));
        dr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drActionPerformed(evt);
            }
        });
        jPanel6.add(dr);
        dr.setBounds(140, 130, 190, 22);

        jIDUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDUSERActionPerformed(evt);
            }
        });
        jPanel6.add(jIDUSER);
        jIDUSER.setBounds(90, 50, 64, 22);

        jLabel20.setText("ID USER");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(100, 30, 41, 16);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\arrow.png")); // NOI18N
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(360, 450, 110, 23);

        detaildokter.setEditable(false);
        detaildokter.setBackground(new java.awt.Color(255, 255, 255));
        detaildokter.setColumns(20);
        detaildokter.setRows(5);
        detaildokter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 0, 12))); // NOI18N
        jScrollPane3.setViewportView(detaildokter);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(340, 50, 280, 100);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField6);
        jTextField6.setBounds(140, 170, 190, 22);

        Riwayat.addTab("Konsultasi", jPanel6);

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        delete2.setBackground(new java.awt.Color(191, 218, 245));
        delete2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\logout (1).png")); // NOI18N
        delete2.setText("Keluar");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Lengkap", "Umur", "Jenis Kelamin", "Alamat", "TTL", "Alergi", "dokter", "Keluhan", "Saran", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Keluhan :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saran :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(delete2)
                        .addGap(56, 56, 56))))
        );

        Riwayat.addTab("Riwayat", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Copyright ©Sarahmanuellaaaa. All rights reserved.");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 36, -1, 50));

        jLabel15.setText("Direktorat Jenderal Perlindungan Konsumen dan Tertib Niaga Kementerian Perdagangan Republik Indonesia 0853 1111 1010 (WhatsApp)");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 16, -1, 50));

        jLabel17.setText("PT Media Dokter Investama Jl. H.R. Rasuna Said Kav B32-33, Jakarta Selatan help@halodoc.com / 021-5095-9900");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -4, -1, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Pictures\\AAA\\1.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void loadRiwayatKonsultasi() {
        try {
            String sql = "SELECT d.id_detail, d.nama, d.umur, d.jnsklmin, d.alamat, d.ttl, d.alergi, doc.nama AS dokter, d.keluhan, d.saran, d.tanggal "
                    + "FROM detail d "
                    + "LEFT JOIN dokter doc ON d.id_dokter = doc.id_dokter "
                    + "WHERE d.id_user = ?";
            PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
            ps.setInt(1, idUser);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_detail"),
                    rs.getString("nama"),
                    rs.getString("umur"),
                    rs.getString("jnsklmin"),
                    rs.getString("alamat"),
                    rs.getString("ttl"),
                    rs.getString("alergi"),
                    rs.getString("dokter"),
                    rs.getString("keluhan"),
                    rs.getString("saran"),
                    rs.getTimestamp("tanggal") // Ambil tanggal dari hasil query
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saat memuat riwayat konsultasi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void LoadNamaDokter() {
        try {
            String sql = "SELECT nama FROM dokter";
            PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                dr.addItem(rs.getString("nama"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadPatientData() {
        try {
            String sql = "SELECT nama, umur, jnsklmin, alamat, alergi, ttl FROM detail WHERE id_user = ?";
            PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
            ps.setInt(1, idUser);
            System.out.println("Mencari data untuk ID User: " + idUser); // Log ID User
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextField1.setText(rs.getString("nama"));
                jTextField3.setText(rs.getString("umur"));
                jTextField4.setText(rs.getString("jnsklmin"));
                jTextField5.setText(rs.getString("alamat"));
                jTextField8.setText(rs.getString("alergi")); // Alergi
                jTextField6.setText(rs.getString("ttl")); // Alergi
            } else {
                JOptionPane.showMessageDialog(this, "Pasien dengan id: " + idUser + " belum menambah informasi data diri,Silahkan tambahkan informasi data diri Anda", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saat memuat data pasien.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Informasi info = new Informasi();
        info.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        HomePage hmpge = new HomePage();
        hmpge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String keluhan = jTextArea1.getText().trim(); // Get the complaint text
        if (keluhan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan isi semua data terlebih dahulu.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (selectedDoctorId <= 0) { // Pastikan dokter telah dipilih
            JOptionPane.showMessageDialog(this, "Silakan pilih dokter.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextField1.getText().trim().isEmpty()
                || jTextField3.getText().trim().isEmpty()
                || jTextField4.getText().trim().isEmpty()
                || jTextField5.getText().trim().isEmpty()
                || jTextField6.getText().trim().isEmpty()
                || jTextField8.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan isi semua data pasien.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (idUser < 0) {
            JOptionPane.showMessageDialog(this, "User  belum menambahkan informasi data diri, silahkan tambahkan data pada label informasi.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nama = getNameById(idUser);
        if (nama == null || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pengguna tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO detail (keluhan, nama, umur, jnsklmin, alamat, ttl, alergi, id_dokter, id_user, tanggal) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);

            ps.setString(1, keluhan);
            ps.setString(2, jTextField1.getText().trim());
            ps.setString(3, jTextField3.getText().trim());
            ps.setString(4, jTextField4.getText().trim());
            ps.setString(5, jTextField5.getText().trim());
            ps.setString(6, jTextField6.getText().trim());
            ps.setString(7, jTextField8.getText().trim());
            ps.setInt(8, selectedDoctorId);
            ps.setInt(9, idUser);
            ps.setTimestamp(10, new java.sql.Timestamp(System.currentTimeMillis())); // Tanggal dan waktu saat ini

            int rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin sudah menginput data diri dan keluhan dengan detail dan benar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Data Yang Anda Input berhasil disimpan.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    jTextArea1.setText("");
                    jInternalFrame1.setVisible(true);
                    loadRiwayatKonsultasi();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAYARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAYARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String selectedBank = (String) jComboBox2.getSelectedItem();
        if ("---Select---".equals(selectedBank)) {
            JOptionPane.showMessageDialog(this, "Silakan pilih metode pembayaran.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(null, "PEMBAYRAN SEDANG DI PROSES MOHON TUNGGU DAN LIHAT INFO SECARA BERTAHAP", "INFORMATION !", JOptionPane.INFORMATION_MESSAGE);
            Riwayat.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jIDUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDUSERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDUSERActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HomePage_1 hmpge1 = new HomePage_1();
        hmpge1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void drActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drActionPerformed
        String selectedDoctor = (String) dr.getSelectedItem();
        if (selectedDoctor != null && !selectedDoctor.equals("---Pilih Dokter---")) {
            StringBuilder infoDokter = new StringBuilder();
            try {
                String sql = "SELECT id_dokter, spesialis, harga FROM dokter WHERE nama = ?";
                PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
                ps.setString(1, selectedDoctor);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    // Ambil ID dokter
                    selectedDoctorId = rs.getInt("id_dokter"); // Ambil ID dokter
                    String spesialis = rs.getString("spesialis");
                    String harga = rs.getString("harga");
                    infoDokter.append("Spesialis: ").append(spesialis).append("\n");
                    infoDokter.append("Harga: ").append(harga).append("\n");
                } else {
                    infoDokter.append("Dokter tidak ditemukan.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

            // Set the details in the text area
            detaildokter.setText(infoDokter.toString());
        }

    }//GEN-LAST:event_drActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String selectedBank = (String) jComboBox2.getSelectedItem();

        if ("BNI".equals(selectedBank)) {
            BAYAR.setText("1500046 ");
        } else if ("BRI".equals(selectedBank)) {
            BAYAR.setText("140171500017");
        } else if ("BCA".equals(selectedBank)) {
            BAYAR.setText("140117");
        } else if ("DANA".equals(selectedBank)) {
            BAYAR.setText("081376822760");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); // Ambil indeks baris yang dipilih
        if (selectedRow != -1) { // Pastikan ada baris yang dipilih
            // Ambil data keluhan dan saran dari model tabel
            String keluhan = jTable1.getValueAt(selectedRow, 8).toString(); // Kolom keluhan
            String saran = jTable1.getValueAt(selectedRow, 9).toString(); // Kolom saran

            // Tampilkan data di JTextArea
            jTextArea2.setText(keluhan); // Tampilkan keluhan
            jTextArea3.setText(saran); // Tampilkan saran
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_delete2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BAYAR;
    private javax.swing.JTabbedPane Riwayat;
    private javax.swing.JButton delete2;
    private javax.swing.JTextArea detaildokter;
    private javax.swing.JComboBox<String> dr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jIDUSER;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private String getNameById(int idUser) {
        String userName = null;
        try {
            String sql = "SELECT nama FROM detail WHERE id_user = ?";
            PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
            ps.setInt(1, idUser);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                userName = rs.getString("nama");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return userName;
    }
}
